version: "3.9"   

services:  
  web:
    build: .
    volumes: 
      - ./myapp:/var/www/html
    ports:  
      - "5000:80"  

  # db:
  #   image: mysql
  #   volumes:
  #     - ./db_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 12345
  #     MYSQL_DATABASE: docker_database
